/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeanIdDelete200Response
 */
export interface BeanIdDelete200Response {
    /**
     * Whether the bean was deleted successfully
     * @type {boolean}
     * @memberof BeanIdDelete200Response
     */
    result?: boolean;
}

/**
 * Check if a given object implements the BeanIdDelete200Response interface.
 */
export function instanceOfBeanIdDelete200Response(value: object): value is BeanIdDelete200Response {
    return true;
}

export function BeanIdDelete200ResponseFromJSON(json: any): BeanIdDelete200Response {
    return BeanIdDelete200ResponseFromJSONTyped(json, false);
}

export function BeanIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeanIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function BeanIdDelete200ResponseToJSON(json: any): BeanIdDelete200Response {
    return BeanIdDelete200ResponseToJSONTyped(json, false);
}

export function BeanIdDelete200ResponseToJSONTyped(value?: BeanIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

