/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeansGet500Response
 */
export interface BeansGet500Response {
    /**
     * Error message
     * @type {string}
     * @memberof BeansGet500Response
     */
    error?: string;
}

/**
 * Check if a given object implements the BeansGet500Response interface.
 */
export function instanceOfBeansGet500Response(value: object): value is BeansGet500Response {
    return true;
}

export function BeansGet500ResponseFromJSON(json: any): BeansGet500Response {
    return BeansGet500ResponseFromJSONTyped(json, false);
}

export function BeansGet500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeansGet500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function BeansGet500ResponseToJSON(json: any): BeansGet500Response {
    return BeansGet500ResponseToJSONTyped(json, false);
}

export function BeansGet500ResponseToJSONTyped(value?: BeansGet500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

