/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BeansGet200ResponseBeansInner } from './BeansGet200ResponseBeansInner';
import {
    BeansGet200ResponseBeansInnerFromJSON,
    BeansGet200ResponseBeansInnerFromJSONTyped,
    BeansGet200ResponseBeansInnerToJSON,
    BeansGet200ResponseBeansInnerToJSONTyped,
} from './BeansGet200ResponseBeansInner';

/**
 * 
 * @export
 * @interface BeansGet200Response
 */
export interface BeansGet200Response {
    /**
     * 
     * @type {Array<BeansGet200ResponseBeansInner>}
     * @memberof BeansGet200Response
     */
    beans?: Array<BeansGet200ResponseBeansInner>;
}

/**
 * Check if a given object implements the BeansGet200Response interface.
 */
export function instanceOfBeansGet200Response(value: object): value is BeansGet200Response {
    return true;
}

export function BeansGet200ResponseFromJSON(json: any): BeansGet200Response {
    return BeansGet200ResponseFromJSONTyped(json, false);
}

export function BeansGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeansGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'beans': json['beans'] == null ? undefined : ((json['beans'] as Array<any>).map(BeansGet200ResponseBeansInnerFromJSON)),
    };
}

export function BeansGet200ResponseToJSON(json: any): BeansGet200Response {
    return BeansGet200ResponseToJSONTyped(json, false);
}

export function BeansGet200ResponseToJSONTyped(value?: BeansGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beans': value['beans'] == null ? undefined : ((value['beans'] as Array<any>).map(BeansGet200ResponseBeansInnerToJSON)),
    };
}

