/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginPostRequest
 */
export interface LoginPostRequest {
    /**
     * User's username
     * @type {string}
     * @memberof LoginPostRequest
     */
    username?: string;
    /**
     * Password of the user
     * @type {string}
     * @memberof LoginPostRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the LoginPostRequest interface.
 */
export function instanceOfLoginPostRequest(value: object): value is LoginPostRequest {
    return true;
}

export function LoginPostRequestFromJSON(json: any): LoginPostRequest {
    return LoginPostRequestFromJSONTyped(json, false);
}

export function LoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function LoginPostRequestToJSON(json: any): LoginPostRequest {
    return LoginPostRequestToJSONTyped(json, false);
}

export function LoginPostRequestToJSONTyped(value?: LoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

