/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginPost200ResponseUser } from './LoginPost200ResponseUser';
import {
    LoginPost200ResponseUserFromJSON,
    LoginPost200ResponseUserFromJSONTyped,
    LoginPost200ResponseUserToJSON,
    LoginPost200ResponseUserToJSONTyped,
} from './LoginPost200ResponseUser';

/**
 * 
 * @export
 * @interface LoginPost200Response
 */
export interface LoginPost200Response {
    /**
     * 
     * @type {LoginPost200ResponseUser}
     * @memberof LoginPost200Response
     */
    user?: LoginPost200ResponseUser;
}

/**
 * Check if a given object implements the LoginPost200Response interface.
 */
export function instanceOfLoginPost200Response(value: object): value is LoginPost200Response {
    return true;
}

export function LoginPost200ResponseFromJSON(json: any): LoginPost200Response {
    return LoginPost200ResponseFromJSONTyped(json, false);
}

export function LoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : LoginPost200ResponseUserFromJSON(json['user']),
    };
}

export function LoginPost200ResponseToJSON(json: any): LoginPost200Response {
    return LoginPost200ResponseToJSONTyped(json, false);
}

export function LoginPost200ResponseToJSONTyped(value?: LoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': LoginPost200ResponseUserToJSON(value['user']),
    };
}

