/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginPost200ResponseUser
 */
export interface LoginPost200ResponseUser {
    /**
     * Unique identifier for the user
     * @type {number}
     * @memberof LoginPost200ResponseUser
     */
    userId?: number;
    /**
     * Username of the user
     * @type {string}
     * @memberof LoginPost200ResponseUser
     */
    username?: string;
    /**
     * JWT token of user
     * @type {string}
     * @memberof LoginPost200ResponseUser
     */
    jwt?: string;
    /**
     * Number of login attempts for the user
     * @type {number}
     * @memberof LoginPost200ResponseUser
     */
    loginAttempts?: number;
    /**
     * First name of the user
     * @type {string}
     * @memberof LoginPost200ResponseUser
     */
    firstName?: string;
    /**
     * Last name of the user
     * @type {string}
     * @memberof LoginPost200ResponseUser
     */
    lastName?: string;
    /**
     * Date and time when the user was created
     * @type {Date}
     * @memberof LoginPost200ResponseUser
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the LoginPost200ResponseUser interface.
 */
export function instanceOfLoginPost200ResponseUser(value: object): value is LoginPost200ResponseUser {
    return true;
}

export function LoginPost200ResponseUserFromJSON(json: any): LoginPost200ResponseUser {
    return LoginPost200ResponseUserFromJSONTyped(json, false);
}

export function LoginPost200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPost200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'username': json['username'] == null ? undefined : json['username'],
        'jwt': json['jwt'] == null ? undefined : json['jwt'],
        'loginAttempts': json['login_attempts'] == null ? undefined : json['login_attempts'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function LoginPost200ResponseUserToJSON(json: any): LoginPost200ResponseUser {
    return LoginPost200ResponseUserToJSONTyped(json, false);
}

export function LoginPost200ResponseUserToJSONTyped(value?: LoginPost200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'username': value['username'],
        'jwt': value['jwt'],
        'login_attempts': value['loginAttempts'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

