/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupPost200Response
 */
export interface SignupPost200Response {
    /**
     * JSON Web Token
     * @type {string}
     * @memberof SignupPost200Response
     */
    jwt?: string;
}

/**
 * Check if a given object implements the SignupPost200Response interface.
 */
export function instanceOfSignupPost200Response(value: object): value is SignupPost200Response {
    return true;
}

export function SignupPost200ResponseFromJSON(json: any): SignupPost200Response {
    return SignupPost200ResponseFromJSONTyped(json, false);
}

export function SignupPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jwt': json['jwt'] == null ? undefined : json['jwt'],
    };
}

export function SignupPost200ResponseToJSON(json: any): SignupPost200Response {
    return SignupPost200ResponseToJSONTyped(json, false);
}

export function SignupPost200ResponseToJSONTyped(value?: SignupPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jwt': value['jwt'],
    };
}

