/* tslint:disable */
/* eslint-disable */
/**
 * Coffee Addiction API
 * Coffee Addiction API swagger documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BeanIdDelete200Response,
  BeansGet200Response,
  BeansGet500Response,
  BeansPost200Response,
  BeansPostRequest,
  LoginPost200Response,
  LoginPostRequest,
  SignupPost200Response,
  SignupPostRequest,
} from '../models/index';
import {
    BeanIdDelete200ResponseFromJSON,
    BeanIdDelete200ResponseToJSON,
    BeansGet200ResponseFromJSON,
    BeansGet200ResponseToJSON,
    BeansGet500ResponseFromJSON,
    BeansGet500ResponseToJSON,
    BeansPost200ResponseFromJSON,
    BeansPost200ResponseToJSON,
    BeansPostRequestFromJSON,
    BeansPostRequestToJSON,
    LoginPost200ResponseFromJSON,
    LoginPost200ResponseToJSON,
    LoginPostRequestFromJSON,
    LoginPostRequestToJSON,
    SignupPost200ResponseFromJSON,
    SignupPost200ResponseToJSON,
    SignupPostRequestFromJSON,
    SignupPostRequestToJSON,
} from '../models/index';

export interface BeanIdDeleteRequest {
    id: number;
}

export interface LoginPostOperationRequest {
    loginPostRequest: LoginPostRequest;
}

export interface SignupPostOperationRequest {
    signupPostRequest: SignupPostRequest;
}

export interface UserBeanCreatePostRequest {
    beansPostRequest: BeansPostRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Deletes a bean owned by the user from the database
     * Deletes a bean owned by the user
     */
    async beanIdDeleteRaw(requestParameters: BeanIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BeanIdDelete200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling beanIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bean/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BeanIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a bean owned by the user from the database
     * Deletes a bean owned by the user
     */
    async beanIdDelete(requestParameters: BeanIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BeanIdDelete200Response> {
        const response = await this.beanIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logs in a user with their email and password
     * Logs in a user
     */
    async loginPostRaw(requestParameters: LoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginPost200Response>> {
        if (requestParameters['loginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'loginPostRequest',
                'Required parameter "loginPostRequest" was null or undefined when calling loginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginPostRequestToJSON(requestParameters['loginPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Logs in a user with their email and password
     * Logs in a user
     */
    async loginPost(requestParameters: LoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginPost200Response> {
        const response = await this.loginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Signs up a new user with their email, password, and other details
     * Signs up a new user
     */
    async signupPostRaw(requestParameters: SignupPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignupPost200Response>> {
        if (requestParameters['signupPostRequest'] == null) {
            throw new runtime.RequiredError(
                'signupPostRequest',
                'Required parameter "signupPostRequest" was null or undefined when calling signupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupPostRequestToJSON(requestParameters['signupPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignupPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Signs up a new user with their email, password, and other details
     * Signs up a new user
     */
    async signupPost(requestParameters: SignupPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignupPost200Response> {
        const response = await this.signupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new bean owned by the user in the database
     * Creates a new bean owned by the user
     */
    async userBeanCreatePostRaw(requestParameters: UserBeanCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BeansPost200Response>> {
        if (requestParameters['beansPostRequest'] == null) {
            throw new runtime.RequiredError(
                'beansPostRequest',
                'Required parameter "beansPostRequest" was null or undefined when calling userBeanCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/bean/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BeansPostRequestToJSON(requestParameters['beansPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BeansPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new bean owned by the user in the database
     * Creates a new bean owned by the user
     */
    async userBeanCreatePost(requestParameters: UserBeanCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BeansPost200Response> {
        const response = await this.userBeanCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a list of beans owned by the user from the database
     * Returns list of beans owned by the user
     */
    async userBeansGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BeansGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/user/beans`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BeansGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a list of beans owned by the user from the database
     * Returns list of beans owned by the user
     */
    async userBeansGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BeansGet200Response> {
        const response = await this.userBeansGetRaw(initOverrides);
        return await response.value();
    }

}
